Add translation for User Badges by v17development
Kakifrucht/flarum-de-extended pull request #2
Opened 2021-05-31 13:29 UTC by derJuba007

2021-05-31 17:39 UTC, Kakifrucht requested changes
Fast perfekt, danke!

2021-05-31 17:39 UTC, Kakifrucht commented on locale/v17development-flarum-user-badges.yml
> +        content: Diese Erweiterung bietet mehr Funktionalität, wenn <a>Auto Moderator</a> installiert und aktiviert ist. Wenn Sie diese Erweiterung installieren, können Benutzer automatisch mit Abzei
Bitte duzen

2021-05-31 17:39 UTC, Kakifrucht commented on locale/v17development-flarum-user-badges.yml
> +      remove_badge:Abzeichen vom Benutzer entfernen
Leerzeichen :)

2021-06-01 15:51 UTC, derJuba007 commented
Erledigt

2021-06-01 18:43 UTC, merged